/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/TodoItems": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["TodoItemDto"][];
                        "application/json": components["schemas"]["TodoItemDto"][];
                        "text/json": components["schemas"]["TodoItemDto"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TodoItemCreateDto"];
                    "text/json": components["schemas"]["TodoItemCreateDto"];
                    "application/*+json": components["schemas"]["TodoItemCreateDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["TodoItemDto"];
                        "application/json": components["schemas"]["TodoItemDto"];
                        "text/json": components["schemas"]["TodoItemDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/TodoItems/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["TodoItemDto"];
                        "application/json": components["schemas"]["TodoItemDto"];
                        "text/json": components["schemas"]["TodoItemDto"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TodoItemUpdateDto"];
                    "text/json": components["schemas"]["TodoItemUpdateDto"];
                    "application/*+json": components["schemas"]["TodoItemUpdateDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/TodoItems/test-error": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        TodoCategory: "ThisEvening" | "TomorrowMorning" | "NextWeek" | "Someday";
        TodoItemCreateDto: {
            title?: string;
            notes?: string;
            isCompleted?: boolean;
            /** Format: date-time */
            dueDate?: string | null;
            category?: components["schemas"]["TodoCategory"];
        };
        TodoItemDto: {
            /** Format: uuid */
            id?: string;
            title?: string;
            notes?: string;
            isCompleted?: boolean;
            /** Format: date-time */
            dueDate?: string | null;
            category?: components["schemas"]["TodoCategory"];
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        TodoItemUpdateDto: {
            /** Format: uuid */
            id?: string;
            title?: string;
            notes?: string;
            isCompleted?: boolean;
            /** Format: date-time */
            dueDate?: string | null;
            category?: components["schemas"]["TodoCategory"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
